from pydantic import BaseModel, ConfigDict, field_validator, model_validator  # Added ConfigDict
from typing import Any, Dict, List, Optional
from enum import Enum  # Added for StoryGenre
from datetime import datetime  # Ensure datetime is imported
from pydantic import Field
from urllib.parse import urlparse


class UserRole(str, Enum):  # Added UserRole Enum
    ADMIN = "admin"
    USER = "user"

# Story Genre Enum (New)


class StoryGenre(str, Enum):
    CHILDRENS = "Children's"
    SCI_FI = "Sci-Fi"
    DRAMA = "Drama"
    HORROR = "Horror"
    ACTION = "Action"
    FANTASY = "Fantasy"  # Added new genre
    MYSTERY = "Mystery"  # Added new genre
    ROMANCE = "Romance"  # Added new genre
    THRILLER = "Thriller"  # Added new genre
    COMEDY = "Comedy"  # Added new genre

# Image Style Enum (FR14)


class ImageStyle(str, Enum):
    DEFAULT = "Default"  # General, vibrant, clear illustration
    CARTOON = "Cartoon"
    WATERCOLOR = "Watercolor"
    PHOTOREALISTIC = "Photorealistic"
    PIXEL_ART = "Pixel Art"
    FANTASY_ART = "Fantasy Art"
    SCI_FI_CONCEPT = "Sci-Fi Concept Art"
    ANIME = "Anime"
    VINTAGE_COMIC = "Vintage Comic Book Art"
    MINIMALIST = "Minimalist"
    NOIR = "Noir"  # Added NOIR

# Word-to-Picture Ratio Enum (FR13)


class WordToPictureRatio(str, Enum):
    PER_PAGE = "One image per page"
    PER_TWO_PAGES = "One image per two pages"
    PER_PARAGRAPH = "One image per paragraph"

# Text Density Enum (New Req)


class TextDensity(str, Enum):
    CONCISE = "Concise (~30-50 words)"  # ~3-4 lines per page
    STANDARD = "Standard (~60-90 words)"  # ~5-7 lines per page
    DETAILED = "Detailed (~100-150 words)"  # ~8-10+ lines per page


class LayoutMode(str, Enum):
    FULL_PAGE_OVERLAY = "full-page-overlay"
    HORIZONTAL_SPLIT = "horizontal-split"
    VERTICAL_SPLIT = "vertical-split"

# Character Detail Schema (New)


class CharacterDetail(BaseModel):
    name: str = Field(..., max_length=100)
    # Made optional as frontend now uses more specific fields
    description: Optional[str] = Field(None, max_length=1000)
    age: Optional[int] = None
    gender: Optional[str] = None
    # E.g., "tall, with long blonde curly hair and blue eyes, often wears a red cloak"
    physical_appearance: Optional[str] = Field(None, max_length=1000)
    # E.g., "medieval armor", "modern casual", "futuristic jumpsuit"
    clothing_style: Optional[str] = Field(None, max_length=500)
    # Broader personality traits, still optional
    personality: Optional[str] = Field(None, max_length=1000)
    # Specific distinguishing traits or habits, e.g., "always carries a locket", "has a noticeable limp"
    key_traits: Optional[str] = Field(None, max_length=500)
    background: Optional[str] = Field(None, max_length=1000)
    # Still optional
    # Path to the generated character reference image
    reference_image_path: Optional[str] = None
    # New field: Detailed description generated by AI from the reference image
    detailed_visual_description_from_reference: Optional[str] = None
    # New field: Revised prompt from DALL-E for the reference image
    reference_image_revised_prompt: Optional[str] = None
    # New field: Gen ID from DALL-E for the reference image (currently will be None)
    reference_image_gen_id: Optional[str] = None

# Page Schemas


class PageBase(BaseModel):
    page_number: int
    text: str
    image_description: Optional[str] = None  # This will be generated by AI


EDITOR_DEFAULTS: Dict[str, Any] = {
    "font_family": "storybook",
    "font_size": 28,
    "font_color": "#ffffff",
    "text_position": "bottom-center",
    "text_box_opacity": 0.6,
    "page_format": "letter",
    "layout_mode": LayoutMode.FULL_PAGE_OVERLAY.value,
}


class StoryEditorSettings(BaseModel):
    font_family: str = Field(default=EDITOR_DEFAULTS["font_family"])
    font_size: int = Field(default=EDITOR_DEFAULTS["font_size"])
    font_color: str = Field(default=EDITOR_DEFAULTS["font_color"])
    text_position: str = Field(default=EDITOR_DEFAULTS["text_position"])
    text_alignment: Optional[str] = Field(None, max_length=20)
    text_box_opacity: float = Field(
        default=EDITOR_DEFAULTS["text_box_opacity"],
        ge=0.0,
        le=1.0,
    )
    page_format: str = Field(default=EDITOR_DEFAULTS["page_format"])
    layout_mode: LayoutMode = Field(default=EDITOR_DEFAULTS["layout_mode"])
    image_fit: Optional[str] = Field(None, max_length=100)
    cover_title_placement: Optional[str] = Field(None, max_length=100)
    readability_treatment: Optional[str] = Field(None, max_length=100)


class PageEditorState(BaseModel):
    original_text: Optional[str] = None
    original_image_path: Optional[str] = None
    text_position: Optional[str] = None
    text_alignment: Optional[str] = None
    font_family: Optional[str] = None
    font_size: Optional[int] = None
    font_color: Optional[str] = None
    text_box_opacity: Optional[float] = Field(None, ge=0.0, le=1.0)


class PageCreate(PageBase):
    # image_path will be added after image generation
    pass


class Page(PageBase):
    id: int
    story_id: int
    image_path: Optional[str] = None  # Path to locally stored image
    editor_state: Optional[dict] = None
    created_at: datetime  # Added
    updated_at: datetime  # Added

    model_config = ConfigDict(from_attributes=True)  # Replaced class Config

# Story Schemas


class StoryBase(BaseModel):
    title: str = Field(..., max_length=200)
    cover_subtitle: Optional[str] = Field(None, max_length=200)
    cover_author: Optional[str] = Field(None, max_length=200)
    genre: str
    story_outline: str = Field(..., max_length=5000)
    # User's initial outline
    main_characters: List[CharacterDetail]
    num_pages: int
    tone: Optional[str] = Field(None, max_length=200)
    setting: Optional[str] = Field(None, max_length=500)
    writing_style: Optional[str] = Field(None, max_length=200)
    # FR14: Added image_style
    image_style: Optional[str] = ImageStyle.DEFAULT.value
    # FR13: Added word_to_picture_ratio
    word_to_picture_ratio: Optional[str] = WordToPictureRatio.PER_PAGE.value
    # New Req: Added text_density
    text_density: Optional[str] = TextDensity.CONCISE.value
    editor_settings: Optional[StoryEditorSettings] = None
    # Add other metadata fields from PRD if necessary
    is_draft: Optional[bool] = True  # For FR24


class StoryCreate(StoryBase):  # This schema is for user input to generate a story
    draft_id: Optional[int] = None
    # Phase 3: allow reusing existing saved Characters by id; these are merged with main_characters
    character_ids: Optional[List[int]] = None


class StoryTitleUpdate(BaseModel):  # New Schema for updating title
    title: str


class StoryListItem(StoryBase):
    id: int
    owner_id: int
    editor_settings: Optional[dict] = None
    generated_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime
    is_hidden: bool = False
    is_deleted: bool = False

    model_config = ConfigDict(from_attributes=True)


class PaginatedStories(BaseModel):
    items: List[StoryListItem]
    total: int
    page: int = Field(1, ge=1)
    page_size: int = Field(20, ge=1, le=100)


class Story(StoryBase):  # This schema is for representing a story, including AI generated title
    id: int
    owner_id: int
    pages: List[Page] = []
    editor_settings: Optional[dict] = None
    generated_at: Optional[datetime] = None  # For FR24
    created_at: datetime  # Added based on previous work
    updated_at: datetime
    # Admin moderation fields
    is_hidden: bool = False
    # Include soft-delete flag for admin views; default False
    is_deleted: bool = False

    model_config = ConfigDict(from_attributes=True)  # Replaced class Config

# User Schemas


class UserBase(BaseModel):
    username: str
    email: Optional[str] = None
    is_active: Optional[bool] = True  # Default to True
    role: Optional[str] = 'user'  # Default to 'user'


class UserCreate(BaseModel):
    username: str
    email: Optional[str] = None
    is_active: Optional[bool] = True
    password: str

    model_config = ConfigDict(extra="ignore")


class User(UserBase):
    id: int
    created_at: datetime
    updated_at: datetime
    # stories: list[Story] = [] # Avoid circular dependency if Story schema also refers to User

    model_config = ConfigDict(from_attributes=True)  # Correctly indented


class UserInDB(User):
    hashed_password: str

# For Admin User Management


class AdminUserUpdate(BaseModel):
    username: Optional[str] = None
    email: Optional[str] = None
    role: Optional[str] = None  # Should be 'user' or 'admin'
    is_active: Optional[bool] = None

    model_config = ConfigDict(from_attributes=True)

# Token Schemas for Authentication


class Token(BaseModel):
    access_token: str
    token_type: str


class ForgotPasswordRequest(BaseModel):
    identifier: str = Field(..., min_length=1, max_length=255)


class ForgotPasswordResponse(BaseModel):
    detail: str
    reset_token_preview: Optional[str] = None


class ResetPasswordConfirm(BaseModel):
    token: str = Field(..., min_length=1)
    new_password: str = Field(..., min_length=1)
    confirm_password: str = Field(..., min_length=1)

    @model_validator(mode="after")
    def validate_password_confirmation(self):
        if self.new_password != self.confirm_password:
            raise ValueError("Passwords do not match")
        return self


class MessageResponse(BaseModel):
    detail: str


class TokenData(BaseModel):
    username: Optional[str] = None

# Dynamic List Schemas (FR-ADM-05)


class DynamicListItemBase(BaseModel):
    item_value: str
    item_label: str
    is_active: bool = True
    sort_order: int = 0
    # For things like OpenAI style mapping
    additional_config: Optional[dict] = None


class DynamicListItemCreate(DynamicListItemBase):
    list_name: str  # Must be provided when creating an item


class DynamicListItem(DynamicListItemBase):
    id: int
    list_name: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DynamicListItemUpdate(BaseModel):
    item_value: Optional[str] = None
    item_label: Optional[str] = None
    is_active: Optional[bool] = None
    sort_order: Optional[int] = None
    additional_config: Optional[dict] = None


class DynamicListItemPublic(BaseModel):
    item_value: str
    item_label: str

    model_config = ConfigDict(from_attributes=True)


class DynamicListBase(BaseModel):
    list_name: str
    list_label: Optional[str] = None  # User-friendly label
    description: Optional[str] = None


class DynamicListCreate(DynamicListBase):
    pass


class DynamicListUpdate(BaseModel):
    list_label: Optional[str] = None  # User-friendly label
    description: Optional[str] = None


class AdminImageStyleMappingRule(BaseModel):
    """Describe the effective OpenAI style mapping for one business style."""

    business_style: str
    image_style_item_id: Optional[int] = None
    image_style_item_label: Optional[str] = None
    image_style_item_active: bool = False
    mapping_item_id: Optional[int] = None
    mapping_item_label: Optional[str] = None
    mapping_item_active: bool = False
    configured_openai_style: Optional[str] = None
    effective_openai_style: str
    source: str
    sort_order: int = 0


class AdminImageStyleMappingState(BaseModel):
    """Summarize the image style mapping state visible in admin tooling."""

    mapping_feature_enabled: bool
    default_openai_style: str
    rules: List[AdminImageStyleMappingRule] = Field(default_factory=list)


class DynamicList(DynamicListBase):
    # items: List[DynamicListItem] = [] # This is loaded via a separate endpoint if needed for full detail
    created_at: datetime
    updated_at: datetime
    # Include items when fetching a full list object
    items: List[DynamicListItem] = []

    model_config = ConfigDict(from_attributes=True)


class DynamicListItemUsage(BaseModel):
    is_in_use: bool
    details: List[str] = []

# Story Generation Task Schemas (New for State Management)


class GenerationTaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class GenerationTaskStep(str, Enum):
    INITIALIZING = "initializing"
    GENERATING_TEXT = "generating_text"
    GENERATING_CHARACTER_IMAGES = "generating_character_images"
    GENERATING_PAGE_IMAGES = "generating_page_images"
    FINALIZING = "finalizing"


class StoryGenerationTaskBase(BaseModel):
    story_id: int
    status: GenerationTaskStatus = GenerationTaskStatus.PENDING
    current_step: GenerationTaskStep = GenerationTaskStep.INITIALIZING
    attempts: int = 0
    last_error: Optional[str] = None
    retry_counts_by_page: Optional[Dict[str, int]] = None
    total_retries: Optional[int] = None
    failed_pages_count: Optional[int] = None


class StoryGenerationTaskCreate(StoryGenerationTaskBase):
    pass


class StoryGenerationTask(StoryGenerationTaskBase):
    id: str
    user_id: int
    progress: int = 0
    created_at: datetime
    updated_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_ms: Optional[int] = None
    last_error: Optional[str] = None
    # Keep legacy transient error field used by services/tests
    error_message: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class StoryEditorPageUpdate(BaseModel):
    id: Optional[int] = None
    page_number: Optional[int] = None
    text: Optional[str] = None
    image_description: Optional[str] = None
    image_path: Optional[str] = None
    editor_state: Optional[PageEditorState] = None


class StoryEditorUpdate(BaseModel):
    title: Optional[str] = None
    cover_subtitle: Optional[str] = Field(None, max_length=200)
    cover_author: Optional[str] = Field(None, max_length=200)
    editor_settings: Optional[StoryEditorSettings] = None
    replace_pages: bool = False
    pages: List[StoryEditorPageUpdate] = []


# --- Characters Domain (Phase 2) ---


class CharacterBase(BaseModel):
    name: str
    description: Optional[str] = None
    age: Optional[int] = None
    gender: Optional[str] = None
    clothing_style: Optional[str] = None
    key_traits: Optional[str] = None
    image_style: Optional[str] = None


class CharacterCreate(CharacterBase):
    generate_image: Optional[bool] = False


class CharacterUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    age: Optional[int] = None
    gender: Optional[str] = None
    clothing_style: Optional[str] = None
    key_traits: Optional[str] = None
    image_style: Optional[str] = None


class CharacterImageOut(BaseModel):
    id: int
    file_path: str
    prompt_used: Optional[str] = None
    image_style: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class CharacterOut(CharacterBase):
    id: int
    created_at: datetime
    updated_at: datetime
    current_image: Optional[CharacterImageOut] = None

    model_config = ConfigDict(from_attributes=True)


class CharacterListItem(BaseModel):
    id: int
    name: str
    updated_at: datetime
    thumbnail_path: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class PaginatedCharacters(BaseModel):
    items: List[CharacterListItem]
    total: int
    page: int = Field(1, ge=1)
    page_size: int = Field(20, ge=1, le=100)


class CharacterThumbnailBackfillResponse(BaseModel):
    """Result summary for an explicit character thumbnail repair run."""

    scanned: int
    repaired: int
    already_public: int
    missing_source: int
    no_private_source: int
    copy_failed: int
    skipped: int


class RegenerateImageRequest(BaseModel):
    description: Optional[str] = None
    image_style: Optional[str] = None


class CharacterPhotoUploadResponse(BaseModel):
    """Response for a successful character photo upload."""

    character_id: int
    content_type: str
    size_bytes: int


class GenerateReferenceFromPhotoRequest(BaseModel):
    """Request to generate a character reference image using an uploaded photo."""

    description: Optional[str] = None
    image_style: Optional[str] = None


# --- Admin Stats Schema ---
class AdminStats(BaseModel):
    total_users: int
    active_users: int
    total_stories: int
    generated_stories: int
    draft_stories: int
    total_characters: int
    tasks_last_24h: int
    tasks_in_progress: int
    tasks_failed_last_24h: int
    tasks_completed_last_24h: int
    avg_task_duration_seconds_last_24h: Optional[float] = None
    success_rate_last_24h: Optional[float] = None  # 0-1 ratio
    # Average attempts across completed tasks in the last 24h (nullable)
    avg_attempts_last_24h: Optional[float] = None


class AdminBroadcastBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    message: str = Field(..., min_length=1, max_length=4000)

    @field_validator("title", "message")
    @classmethod
    def _normalize_broadcast_text(cls, value: str) -> str:
        """Trim broadcast text fields and reject blank values."""

        normalized = value.strip()
        if not normalized:
            raise ValueError("Broadcast fields cannot be empty.")
        return normalized


class AdminBroadcastCreate(AdminBroadcastBase):
    pass


class AdminBroadcast(AdminBroadcastBase):
    id: int
    target_scope: str
    status: str
    recipient_count: int
    created_by_user_id: int
    created_at: datetime
    sent_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AdminAnalyticsSummary(BaseModel):
    users_registered_last_7d: int
    stories_created_last_7d: int
    stories_generated_last_7d: int
    characters_created_last_7d: int
    active_story_authors_last_7d: int
    generation_success_rate_last_7d: Optional[float] = None
    broadcasts_sent_last_30d: int
    broadcast_recipients_last_30d: int


class AdminConfigUpdate(BaseModel):
    """Validated safe subset of runtime configuration editable by admins."""

    openai_text_provider: Optional[str] = Field(None, max_length=50)
    openai_text_base_url: Optional[str] = Field(None, max_length=255)
    openai_image_provider: Optional[str] = Field(None, max_length=50)
    openai_image_base_url: Optional[str] = Field(None, max_length=255)
    text_model: Optional[str] = Field(None, max_length=100)
    image_model: Optional[str] = Field(None, max_length=100)
    enable_image_generation: Optional[bool] = None
    use_openai_responses_api: Optional[bool] = None
    openai_text_enable_fallback: Optional[bool] = None
    enable_image_style_mapping: Optional[bool] = None

    model_config = ConfigDict(extra="forbid")

    @field_validator(
        "openai_text_provider",
        "openai_image_provider",
        "openai_text_base_url",
        "openai_image_base_url",
        "text_model",
        "image_model",
        mode="before",
    )
    @classmethod
    def _normalize_optional_string(cls, value: Optional[str]) -> Optional[str]:
        """Trim optional string values and treat blanks as cleared overrides."""

        if value is None:
            return None
        normalized = str(value).strip()
        return normalized or None

    @field_validator("openai_text_provider", "openai_image_provider")
    @classmethod
    def _validate_provider(cls, value: Optional[str]) -> Optional[str]:
        """Restrict provider labels to a small safe character set."""

        if value is None:
            return value
        if not all(char.isalnum() or char in {"-", "_"} for char in value):
            raise ValueError(
                "Provider values may only use letters, numbers, hyphens, or underscores."
            )
        return value

    @field_validator("openai_text_base_url", "openai_image_base_url")
    @classmethod
    def _validate_base_url(cls, value: Optional[str]) -> Optional[str]:
        """Allow only http(s) OpenAI-compatible base URLs."""

        if value is None:
            return value
        parsed = urlparse(value)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ValueError("Base URL must be a valid http or https URL.")
        return value.rstrip("/")


class AdminConfigFieldMetadata(BaseModel):
    """Frontend metadata for an editable admin config field."""

    label: str
    input_type: str
    help_text: str
    can_clear: bool = False


# --- Admin Moderation Requests ---
class HideStoryRequest(BaseModel):
    is_hidden: bool
